# CMake generated Testfile for 
# Source directory: /home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/examples/traffic-control
# Build directory: /home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/cmake-cache/examples/traffic-control
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-traffic-control "ns3.36.1-traffic-control-default")
set_tests_properties(ctest-traffic-control PROPERTIES  WORKING_DIRECTORY "/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1506;set_runtime_outputdirectory;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/examples/traffic-control/CMakeLists.txt;1;build_example;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/examples/traffic-control/CMakeLists.txt;0;")
add_test(ctest-queue-discs-benchmark "ns3.36.1-queue-discs-benchmark-default")
set_tests_properties(ctest-queue-discs-benchmark PROPERTIES  WORKING_DIRECTORY "/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1506;set_runtime_outputdirectory;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/examples/traffic-control/CMakeLists.txt;12;build_example;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/examples/traffic-control/CMakeLists.txt;0;")
add_test(ctest-red-vs-fengadaptive "ns3.36.1-red-vs-fengadaptive-default")
set_tests_properties(ctest-red-vs-fengadaptive PROPERTIES  WORKING_DIRECTORY "/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1506;set_runtime_outputdirectory;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/examples/traffic-control/CMakeLists.txt;24;build_example;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/examples/traffic-control/CMakeLists.txt;0;")
add_test(ctest-red-vs-nlred "ns3.36.1-red-vs-nlred-default")
set_tests_properties(ctest-red-vs-nlred PROPERTIES  WORKING_DIRECTORY "/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1506;set_runtime_outputdirectory;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/examples/traffic-control/CMakeLists.txt;35;build_example;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/examples/traffic-control/CMakeLists.txt;0;")
add_test(ctest-tbf-example "ns3.36.1-tbf-example-default")
set_tests_properties(ctest-tbf-example PROPERTIES  WORKING_DIRECTORY "/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1506;set_runtime_outputdirectory;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/examples/traffic-control/CMakeLists.txt;46;build_example;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/examples/traffic-control/CMakeLists.txt;0;")
add_test(ctest-cobalt-vs-codel "ns3.36.1-cobalt-vs-codel-default")
set_tests_properties(ctest-cobalt-vs-codel PROPERTIES  WORKING_DIRECTORY "/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build/examples/traffic-control/" _BACKTRACE_TRIPLES "/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1506;set_runtime_outputdirectory;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/examples/traffic-control/CMakeLists.txt;56;build_example;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/examples/traffic-control/CMakeLists.txt;0;")
