# CMake generated Testfile for 
# Source directory: /home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/src/tap-bridge/examples
# Build directory: /home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/cmake-cache/src/tap-bridge/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-tap-csma "ns3.36.1-tap-csma-default")
set_tests_properties(ctest-tap-csma PROPERTIES  WORKING_DIRECTORY "/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build/src/tap-bridge/examples/" _BACKTRACE_TRIPLES "/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/src/tap-bridge/examples/CMakeLists.txt;2;build_lib_example;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/src/tap-bridge/examples/CMakeLists.txt;0;")
add_test(ctest-tap-csma-virtual-machine "ns3.36.1-tap-csma-virtual-machine-default")
set_tests_properties(ctest-tap-csma-virtual-machine PROPERTIES  WORKING_DIRECTORY "/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build/src/tap-bridge/examples/" _BACKTRACE_TRIPLES "/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/src/tap-bridge/examples/CMakeLists.txt;12;build_lib_example;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/src/tap-bridge/examples/CMakeLists.txt;0;")
add_test(ctest-tap-wifi-virtual-machine "ns3.36.1-tap-wifi-virtual-machine-default")
set_tests_properties(ctest-tap-wifi-virtual-machine PROPERTIES  WORKING_DIRECTORY "/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build/src/tap-bridge/examples/" _BACKTRACE_TRIPLES "/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/src/tap-bridge/examples/CMakeLists.txt;21;build_lib_example;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/src/tap-bridge/examples/CMakeLists.txt;0;")
add_test(ctest-tap-wifi-dumbbell "ns3.36.1-tap-wifi-dumbbell-default")
set_tests_properties(ctest-tap-wifi-dumbbell PROPERTIES  WORKING_DIRECTORY "/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build/src/tap-bridge/examples/" _BACKTRACE_TRIPLES "/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/src/tap-bridge/examples/CMakeLists.txt;32;build_lib_example;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/src/tap-bridge/examples/CMakeLists.txt;0;")
