# CMake generated Testfile for 
# Source directory: /home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/examples/socket
# Build directory: /home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/cmake-cache/examples/socket
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-socket-bound-static-routing "ns3.36.1-socket-bound-static-routing-default")
set_tests_properties(ctest-socket-bound-static-routing PROPERTIES  WORKING_DIRECTORY "/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build/examples/socket/" _BACKTRACE_TRIPLES "/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1506;set_runtime_outputdirectory;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/examples/socket/CMakeLists.txt;1;build_example;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/examples/socket/CMakeLists.txt;0;")
add_test(ctest-socket-bound-tcp-static-routing "ns3.36.1-socket-bound-tcp-static-routing-default")
set_tests_properties(ctest-socket-bound-tcp-static-routing PROPERTIES  WORKING_DIRECTORY "/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build/examples/socket/" _BACKTRACE_TRIPLES "/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1506;set_runtime_outputdirectory;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/examples/socket/CMakeLists.txt;11;build_example;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/examples/socket/CMakeLists.txt;0;")
add_test(ctest-socket-options-ipv4 "ns3.36.1-socket-options-ipv4-default")
set_tests_properties(ctest-socket-options-ipv4 PROPERTIES  WORKING_DIRECTORY "/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build/examples/socket/" _BACKTRACE_TRIPLES "/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1506;set_runtime_outputdirectory;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/examples/socket/CMakeLists.txt;22;build_example;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/examples/socket/CMakeLists.txt;0;")
add_test(ctest-socket-options-ipv6 "ns3.36.1-socket-options-ipv6-default")
set_tests_properties(ctest-socket-options-ipv6 PROPERTIES  WORKING_DIRECTORY "/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build/examples/socket/" _BACKTRACE_TRIPLES "/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1506;set_runtime_outputdirectory;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/examples/socket/CMakeLists.txt;32;build_example;/home/minseo/snu_project/ns-allinone-3.36.1/ns-3.36.1/examples/socket/CMakeLists.txt;0;")
